export default [
  {"url": "sns/getToken", "isNeedToken": false},
  {"url": "sns/wxdecrypt"},
  {"url": "sns/wxdecryptWithNoLogin", "isNeedToken": false},
  {"url": "sns/wxLogin", "isNeedToken": false},
  {"url": "sns/sendVerifyCode"},
  {"url": "sns/phoneBind"},
  {"url": "sns/wxqrcode"},
  {"url": "sns/genShareImgArticle"},
  {"url": "sns/genShareImgColumn"},
  {"url": "service/start"},
  {"url": "comment/list"},
  {"url": "comment/add"},
  {"url": "comment/listSecond"},
  {"url": "comment/praiseAdd"},
  {"url": "comment/praiseDel"},
  {"url": "comment/listV2"},
  {"url": "comment/detailById"},
  {"url": "article/add"},
  {"url": "article/list"},
  {"url": "article/discovery", "isNeedToken": false},
  {"url": "article/detail"},
  {"url": "article/update"},
  {"url": "article/forceDelete"},
  {"url": "article/setting"},
  {"url": "article/privacy"},
  {"url": "article/theme"},
  {"url": "article/privacy"},
  {"url": "article/pwdtoken"},
  {"url": "article/totalCount", "isNeedToken": false},
  {"url": "follow/follower"},
  {"url": "follow/fansList"},
  {"url": "upload/batchToken"},
  {"url": "upload/videoThumb"}
]